// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: storage/entities.proto

#include "storage/entities.pb.h"
#include "storage/entities.grpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace grpc_services {
namespace storage {

}  // namespace grpc_services
}  // namespace storage

