// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: storage/storage.proto

#include "storage/storage.pb.h"
#include "storage/storage.grpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace grpc_services {
namespace storage {

static const char* StorageService_method_names[] = {
  "/grpc_services.storage.StorageService/GetDrive",
  "/grpc_services.storage.StorageService/GetDrives",
  "/grpc_services.storage.StorageService/GetItem",
  "/grpc_services.storage.StorageService/GetChildren",
  "/grpc_services.storage.StorageService/GetContent",
  "/grpc_services.storage.StorageService/GetContentStream",
  "/grpc_services.storage.StorageService/CreateDrive",
  "/grpc_services.storage.StorageService/CreateItem",
  "/grpc_services.storage.StorageService/PutContentStream",
  "/grpc_services.storage.StorageService/TruncateContent",
  "/grpc_services.storage.StorageService/UpdateDrive",
  "/grpc_services.storage.StorageService/UpdateItem",
  "/grpc_services.storage.StorageService/RemoveDrive",
  "/grpc_services.storage.StorageService/RemoveItem",
  "/grpc_services.storage.StorageService/WatchChanges",
};

std::unique_ptr< StorageService::Stub> StorageService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< StorageService::Stub> stub(new StorageService::Stub(channel));
  return stub;
}

StorageService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_GetDrive_(StorageService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetDrives_(StorageService_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetItem_(StorageService_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetChildren_(StorageService_method_names[3], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetContent_(StorageService_method_names[4], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetContentStream_(StorageService_method_names[5], ::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_CreateDrive_(StorageService_method_names[6], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CreateItem_(StorageService_method_names[7], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PutContentStream_(StorageService_method_names[8], ::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  , rpcmethod_TruncateContent_(StorageService_method_names[9], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateDrive_(StorageService_method_names[10], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateItem_(StorageService_method_names[11], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RemoveDrive_(StorageService_method_names[12], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RemoveItem_(StorageService_method_names[13], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_WatchChanges_(StorageService_method_names[14], ::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::Status StorageService::Stub::GetDrive(::grpc::ClientContext* context, const ::grpc_services::storage::GetDriveRequest& request, ::grpc_services::storage::GetDriveResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetDrive_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::grpc_services::storage::GetDriveResponse>* StorageService::Stub::AsyncGetDriveRaw(::grpc::ClientContext* context, const ::grpc_services::storage::GetDriveRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::grpc_services::storage::GetDriveResponse>::Create(channel_.get(), cq, rpcmethod_GetDrive_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::grpc_services::storage::GetDriveResponse>* StorageService::Stub::PrepareAsyncGetDriveRaw(::grpc::ClientContext* context, const ::grpc_services::storage::GetDriveRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::grpc_services::storage::GetDriveResponse>::Create(channel_.get(), cq, rpcmethod_GetDrive_, context, request, false);
}

::grpc::Status StorageService::Stub::GetDrives(::grpc::ClientContext* context, const ::grpc_services::storage::GetDrivesRequest& request, ::grpc_services::storage::GetDrivesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetDrives_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::grpc_services::storage::GetDrivesResponse>* StorageService::Stub::AsyncGetDrivesRaw(::grpc::ClientContext* context, const ::grpc_services::storage::GetDrivesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::grpc_services::storage::GetDrivesResponse>::Create(channel_.get(), cq, rpcmethod_GetDrives_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::grpc_services::storage::GetDrivesResponse>* StorageService::Stub::PrepareAsyncGetDrivesRaw(::grpc::ClientContext* context, const ::grpc_services::storage::GetDrivesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::grpc_services::storage::GetDrivesResponse>::Create(channel_.get(), cq, rpcmethod_GetDrives_, context, request, false);
}

::grpc::Status StorageService::Stub::GetItem(::grpc::ClientContext* context, const ::grpc_services::storage::GetItemRequest& request, ::grpc_services::storage::GetItemResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetItem_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::grpc_services::storage::GetItemResponse>* StorageService::Stub::AsyncGetItemRaw(::grpc::ClientContext* context, const ::grpc_services::storage::GetItemRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::grpc_services::storage::GetItemResponse>::Create(channel_.get(), cq, rpcmethod_GetItem_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::grpc_services::storage::GetItemResponse>* StorageService::Stub::PrepareAsyncGetItemRaw(::grpc::ClientContext* context, const ::grpc_services::storage::GetItemRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::grpc_services::storage::GetItemResponse>::Create(channel_.get(), cq, rpcmethod_GetItem_, context, request, false);
}

::grpc::Status StorageService::Stub::GetChildren(::grpc::ClientContext* context, const ::grpc_services::storage::GetChildrenRequest& request, ::grpc_services::storage::GetChildrenResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetChildren_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::grpc_services::storage::GetChildrenResponse>* StorageService::Stub::AsyncGetChildrenRaw(::grpc::ClientContext* context, const ::grpc_services::storage::GetChildrenRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::grpc_services::storage::GetChildrenResponse>::Create(channel_.get(), cq, rpcmethod_GetChildren_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::grpc_services::storage::GetChildrenResponse>* StorageService::Stub::PrepareAsyncGetChildrenRaw(::grpc::ClientContext* context, const ::grpc_services::storage::GetChildrenRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::grpc_services::storage::GetChildrenResponse>::Create(channel_.get(), cq, rpcmethod_GetChildren_, context, request, false);
}

::grpc::Status StorageService::Stub::GetContent(::grpc::ClientContext* context, const ::grpc_services::storage::GetContentRequest& request, ::grpc_services::storage::GetContentResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetContent_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::grpc_services::storage::GetContentResponse>* StorageService::Stub::AsyncGetContentRaw(::grpc::ClientContext* context, const ::grpc_services::storage::GetContentRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::grpc_services::storage::GetContentResponse>::Create(channel_.get(), cq, rpcmethod_GetContent_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::grpc_services::storage::GetContentResponse>* StorageService::Stub::PrepareAsyncGetContentRaw(::grpc::ClientContext* context, const ::grpc_services::storage::GetContentRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::grpc_services::storage::GetContentResponse>::Create(channel_.get(), cq, rpcmethod_GetContent_, context, request, false);
}

::grpc::ClientReader< ::grpc_services::storage::GetContentStreamResponse>* StorageService::Stub::GetContentStreamRaw(::grpc::ClientContext* context, const ::grpc_services::storage::GetContentStreamRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::grpc_services::storage::GetContentStreamResponse>::Create(channel_.get(), rpcmethod_GetContentStream_, context, request);
}

::grpc::ClientAsyncReader< ::grpc_services::storage::GetContentStreamResponse>* StorageService::Stub::AsyncGetContentStreamRaw(::grpc::ClientContext* context, const ::grpc_services::storage::GetContentStreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::grpc_services::storage::GetContentStreamResponse>::Create(channel_.get(), cq, rpcmethod_GetContentStream_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::grpc_services::storage::GetContentStreamResponse>* StorageService::Stub::PrepareAsyncGetContentStreamRaw(::grpc::ClientContext* context, const ::grpc_services::storage::GetContentStreamRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::grpc_services::storage::GetContentStreamResponse>::Create(channel_.get(), cq, rpcmethod_GetContentStream_, context, request, false, nullptr);
}

::grpc::Status StorageService::Stub::CreateDrive(::grpc::ClientContext* context, const ::grpc_services::storage::CreateDriveRequest& request, ::grpc_services::storage::CreateDriveResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_CreateDrive_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::grpc_services::storage::CreateDriveResponse>* StorageService::Stub::AsyncCreateDriveRaw(::grpc::ClientContext* context, const ::grpc_services::storage::CreateDriveRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::grpc_services::storage::CreateDriveResponse>::Create(channel_.get(), cq, rpcmethod_CreateDrive_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::grpc_services::storage::CreateDriveResponse>* StorageService::Stub::PrepareAsyncCreateDriveRaw(::grpc::ClientContext* context, const ::grpc_services::storage::CreateDriveRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::grpc_services::storage::CreateDriveResponse>::Create(channel_.get(), cq, rpcmethod_CreateDrive_, context, request, false);
}

::grpc::Status StorageService::Stub::CreateItem(::grpc::ClientContext* context, const ::grpc_services::storage::CreateItemRequest& request, ::grpc_services::storage::CreateItemResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_CreateItem_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::grpc_services::storage::CreateItemResponse>* StorageService::Stub::AsyncCreateItemRaw(::grpc::ClientContext* context, const ::grpc_services::storage::CreateItemRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::grpc_services::storage::CreateItemResponse>::Create(channel_.get(), cq, rpcmethod_CreateItem_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::grpc_services::storage::CreateItemResponse>* StorageService::Stub::PrepareAsyncCreateItemRaw(::grpc::ClientContext* context, const ::grpc_services::storage::CreateItemRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::grpc_services::storage::CreateItemResponse>::Create(channel_.get(), cq, rpcmethod_CreateItem_, context, request, false);
}

::grpc::ClientWriter< ::grpc_services::storage::PutContentStreamRequest>* StorageService::Stub::PutContentStreamRaw(::grpc::ClientContext* context, ::grpc_services::storage::PutContentStreamResponse* response) {
  return ::grpc::internal::ClientWriterFactory< ::grpc_services::storage::PutContentStreamRequest>::Create(channel_.get(), rpcmethod_PutContentStream_, context, response);
}

::grpc::ClientAsyncWriter< ::grpc_services::storage::PutContentStreamRequest>* StorageService::Stub::AsyncPutContentStreamRaw(::grpc::ClientContext* context, ::grpc_services::storage::PutContentStreamResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::grpc_services::storage::PutContentStreamRequest>::Create(channel_.get(), cq, rpcmethod_PutContentStream_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::grpc_services::storage::PutContentStreamRequest>* StorageService::Stub::PrepareAsyncPutContentStreamRaw(::grpc::ClientContext* context, ::grpc_services::storage::PutContentStreamResponse* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::grpc_services::storage::PutContentStreamRequest>::Create(channel_.get(), cq, rpcmethod_PutContentStream_, context, response, false, nullptr);
}

::grpc::Status StorageService::Stub::TruncateContent(::grpc::ClientContext* context, const ::grpc_services::storage::TruncateContentRequest& request, ::grpc_services::storage::TruncateContentResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_TruncateContent_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::grpc_services::storage::TruncateContentResponse>* StorageService::Stub::AsyncTruncateContentRaw(::grpc::ClientContext* context, const ::grpc_services::storage::TruncateContentRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::grpc_services::storage::TruncateContentResponse>::Create(channel_.get(), cq, rpcmethod_TruncateContent_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::grpc_services::storage::TruncateContentResponse>* StorageService::Stub::PrepareAsyncTruncateContentRaw(::grpc::ClientContext* context, const ::grpc_services::storage::TruncateContentRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::grpc_services::storage::TruncateContentResponse>::Create(channel_.get(), cq, rpcmethod_TruncateContent_, context, request, false);
}

::grpc::Status StorageService::Stub::UpdateDrive(::grpc::ClientContext* context, const ::grpc_services::storage::UpdateDriveRequest& request, ::grpc_services::storage::UpdateDriveResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_UpdateDrive_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::grpc_services::storage::UpdateDriveResponse>* StorageService::Stub::AsyncUpdateDriveRaw(::grpc::ClientContext* context, const ::grpc_services::storage::UpdateDriveRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::grpc_services::storage::UpdateDriveResponse>::Create(channel_.get(), cq, rpcmethod_UpdateDrive_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::grpc_services::storage::UpdateDriveResponse>* StorageService::Stub::PrepareAsyncUpdateDriveRaw(::grpc::ClientContext* context, const ::grpc_services::storage::UpdateDriveRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::grpc_services::storage::UpdateDriveResponse>::Create(channel_.get(), cq, rpcmethod_UpdateDrive_, context, request, false);
}

::grpc::Status StorageService::Stub::UpdateItem(::grpc::ClientContext* context, const ::grpc_services::storage::UpdateItemRequest& request, ::grpc_services::storage::UpdateItemResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_UpdateItem_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::grpc_services::storage::UpdateItemResponse>* StorageService::Stub::AsyncUpdateItemRaw(::grpc::ClientContext* context, const ::grpc_services::storage::UpdateItemRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::grpc_services::storage::UpdateItemResponse>::Create(channel_.get(), cq, rpcmethod_UpdateItem_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::grpc_services::storage::UpdateItemResponse>* StorageService::Stub::PrepareAsyncUpdateItemRaw(::grpc::ClientContext* context, const ::grpc_services::storage::UpdateItemRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::grpc_services::storage::UpdateItemResponse>::Create(channel_.get(), cq, rpcmethod_UpdateItem_, context, request, false);
}

::grpc::Status StorageService::Stub::RemoveDrive(::grpc::ClientContext* context, const ::grpc_services::storage::RemoveDriveRequest& request, ::grpc_services::storage::RemoveDriveResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_RemoveDrive_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::grpc_services::storage::RemoveDriveResponse>* StorageService::Stub::AsyncRemoveDriveRaw(::grpc::ClientContext* context, const ::grpc_services::storage::RemoveDriveRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::grpc_services::storage::RemoveDriveResponse>::Create(channel_.get(), cq, rpcmethod_RemoveDrive_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::grpc_services::storage::RemoveDriveResponse>* StorageService::Stub::PrepareAsyncRemoveDriveRaw(::grpc::ClientContext* context, const ::grpc_services::storage::RemoveDriveRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::grpc_services::storage::RemoveDriveResponse>::Create(channel_.get(), cq, rpcmethod_RemoveDrive_, context, request, false);
}

::grpc::Status StorageService::Stub::RemoveItem(::grpc::ClientContext* context, const ::grpc_services::storage::RemoveItemRequest& request, ::grpc_services::storage::RemoveItemResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_RemoveItem_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::grpc_services::storage::RemoveItemResponse>* StorageService::Stub::AsyncRemoveItemRaw(::grpc::ClientContext* context, const ::grpc_services::storage::RemoveItemRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::grpc_services::storage::RemoveItemResponse>::Create(channel_.get(), cq, rpcmethod_RemoveItem_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::grpc_services::storage::RemoveItemResponse>* StorageService::Stub::PrepareAsyncRemoveItemRaw(::grpc::ClientContext* context, const ::grpc_services::storage::RemoveItemRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::grpc_services::storage::RemoveItemResponse>::Create(channel_.get(), cq, rpcmethod_RemoveItem_, context, request, false);
}

::grpc::ClientReader< ::grpc_services::storage::WatchChangesResponse>* StorageService::Stub::WatchChangesRaw(::grpc::ClientContext* context, const ::grpc_services::storage::WatchChangesRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::grpc_services::storage::WatchChangesResponse>::Create(channel_.get(), rpcmethod_WatchChanges_, context, request);
}

::grpc::ClientAsyncReader< ::grpc_services::storage::WatchChangesResponse>* StorageService::Stub::AsyncWatchChangesRaw(::grpc::ClientContext* context, const ::grpc_services::storage::WatchChangesRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::grpc_services::storage::WatchChangesResponse>::Create(channel_.get(), cq, rpcmethod_WatchChanges_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::grpc_services::storage::WatchChangesResponse>* StorageService::Stub::PrepareAsyncWatchChangesRaw(::grpc::ClientContext* context, const ::grpc_services::storage::WatchChangesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::grpc_services::storage::WatchChangesResponse>::Create(channel_.get(), cq, rpcmethod_WatchChanges_, context, request, false, nullptr);
}

StorageService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StorageService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StorageService::Service, ::grpc_services::storage::GetDriveRequest, ::grpc_services::storage::GetDriveResponse>(
          std::mem_fn(&StorageService::Service::GetDrive), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StorageService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StorageService::Service, ::grpc_services::storage::GetDrivesRequest, ::grpc_services::storage::GetDrivesResponse>(
          std::mem_fn(&StorageService::Service::GetDrives), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StorageService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StorageService::Service, ::grpc_services::storage::GetItemRequest, ::grpc_services::storage::GetItemResponse>(
          std::mem_fn(&StorageService::Service::GetItem), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StorageService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StorageService::Service, ::grpc_services::storage::GetChildrenRequest, ::grpc_services::storage::GetChildrenResponse>(
          std::mem_fn(&StorageService::Service::GetChildren), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StorageService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StorageService::Service, ::grpc_services::storage::GetContentRequest, ::grpc_services::storage::GetContentResponse>(
          std::mem_fn(&StorageService::Service::GetContent), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StorageService_method_names[5],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< StorageService::Service, ::grpc_services::storage::GetContentStreamRequest, ::grpc_services::storage::GetContentStreamResponse>(
          std::mem_fn(&StorageService::Service::GetContentStream), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StorageService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StorageService::Service, ::grpc_services::storage::CreateDriveRequest, ::grpc_services::storage::CreateDriveResponse>(
          std::mem_fn(&StorageService::Service::CreateDrive), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StorageService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StorageService::Service, ::grpc_services::storage::CreateItemRequest, ::grpc_services::storage::CreateItemResponse>(
          std::mem_fn(&StorageService::Service::CreateItem), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StorageService_method_names[8],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< StorageService::Service, ::grpc_services::storage::PutContentStreamRequest, ::grpc_services::storage::PutContentStreamResponse>(
          std::mem_fn(&StorageService::Service::PutContentStream), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StorageService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StorageService::Service, ::grpc_services::storage::TruncateContentRequest, ::grpc_services::storage::TruncateContentResponse>(
          std::mem_fn(&StorageService::Service::TruncateContent), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StorageService_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StorageService::Service, ::grpc_services::storage::UpdateDriveRequest, ::grpc_services::storage::UpdateDriveResponse>(
          std::mem_fn(&StorageService::Service::UpdateDrive), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StorageService_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StorageService::Service, ::grpc_services::storage::UpdateItemRequest, ::grpc_services::storage::UpdateItemResponse>(
          std::mem_fn(&StorageService::Service::UpdateItem), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StorageService_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StorageService::Service, ::grpc_services::storage::RemoveDriveRequest, ::grpc_services::storage::RemoveDriveResponse>(
          std::mem_fn(&StorageService::Service::RemoveDrive), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StorageService_method_names[13],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StorageService::Service, ::grpc_services::storage::RemoveItemRequest, ::grpc_services::storage::RemoveItemResponse>(
          std::mem_fn(&StorageService::Service::RemoveItem), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StorageService_method_names[14],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< StorageService::Service, ::grpc_services::storage::WatchChangesRequest, ::grpc_services::storage::WatchChangesResponse>(
          std::mem_fn(&StorageService::Service::WatchChanges), this)));
}

StorageService::Service::~Service() {
}

::grpc::Status StorageService::Service::GetDrive(::grpc::ServerContext* context, const ::grpc_services::storage::GetDriveRequest* request, ::grpc_services::storage::GetDriveResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StorageService::Service::GetDrives(::grpc::ServerContext* context, const ::grpc_services::storage::GetDrivesRequest* request, ::grpc_services::storage::GetDrivesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StorageService::Service::GetItem(::grpc::ServerContext* context, const ::grpc_services::storage::GetItemRequest* request, ::grpc_services::storage::GetItemResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StorageService::Service::GetChildren(::grpc::ServerContext* context, const ::grpc_services::storage::GetChildrenRequest* request, ::grpc_services::storage::GetChildrenResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StorageService::Service::GetContent(::grpc::ServerContext* context, const ::grpc_services::storage::GetContentRequest* request, ::grpc_services::storage::GetContentResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StorageService::Service::GetContentStream(::grpc::ServerContext* context, const ::grpc_services::storage::GetContentStreamRequest* request, ::grpc::ServerWriter< ::grpc_services::storage::GetContentStreamResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StorageService::Service::CreateDrive(::grpc::ServerContext* context, const ::grpc_services::storage::CreateDriveRequest* request, ::grpc_services::storage::CreateDriveResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StorageService::Service::CreateItem(::grpc::ServerContext* context, const ::grpc_services::storage::CreateItemRequest* request, ::grpc_services::storage::CreateItemResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StorageService::Service::PutContentStream(::grpc::ServerContext* context, ::grpc::ServerReader< ::grpc_services::storage::PutContentStreamRequest>* reader, ::grpc_services::storage::PutContentStreamResponse* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StorageService::Service::TruncateContent(::grpc::ServerContext* context, const ::grpc_services::storage::TruncateContentRequest* request, ::grpc_services::storage::TruncateContentResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StorageService::Service::UpdateDrive(::grpc::ServerContext* context, const ::grpc_services::storage::UpdateDriveRequest* request, ::grpc_services::storage::UpdateDriveResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StorageService::Service::UpdateItem(::grpc::ServerContext* context, const ::grpc_services::storage::UpdateItemRequest* request, ::grpc_services::storage::UpdateItemResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StorageService::Service::RemoveDrive(::grpc::ServerContext* context, const ::grpc_services::storage::RemoveDriveRequest* request, ::grpc_services::storage::RemoveDriveResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StorageService::Service::RemoveItem(::grpc::ServerContext* context, const ::grpc_services::storage::RemoveItemRequest* request, ::grpc_services::storage::RemoveItemResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StorageService::Service::WatchChanges(::grpc::ServerContext* context, const ::grpc_services::storage::WatchChangesRequest* request, ::grpc::ServerWriter< ::grpc_services::storage::WatchChangesResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace grpc_services
}  // namespace storage

